name: sparcl

services:
  sparcl:
    image: frontend
    build:
      dockerfile: ./Dockerfile
      args:
        - VITE_SSD_ROOT_URL=${VITE_SSD_ROOT_URL}
        - VITE_AUTH_AUTH0_DOMAIN=${VITE_AUTH_AUTH0_DOMAIN}
        - VITE_AUTH_AUTH0_CLIENTID=${VITE_AUTH_AUTH0_CLIENTID}
        - VITE_NOAUTH=${VITE_NOAUTH}
        - VITE_NOAUTH_USER_NAME=${VITE_NOAUTH_USER_NAME}
        - VITE_NOAUTH_USER_EMAIL=${VITE_NOAUTH_USER_EMAIL}
        - VITE_AUTH_REDIRECT_URI=${VITE_AUTH_REDIRECT_URI}
        - VITE_RMQ_TOPIC_GEOPOSE_UPDATE=${VITE_RMQ_TOPIC_GEOPOSE_UPDATE}
        - VITE_RMQ_TOPIC_OBJECT_CREATED=${VITE_RMQ_TOPIC_OBJECT_CREATED}
        - VITE_RMQ_TOPIC_SENSOR_UPDATE=${VITE_RMQ_TOPIC_SENSOR_UPDATE}
        - VITE_RMQ_TOPIC_RETICLE_UPDATE=${VITE_RMQ_TOPIC_RETICLE_UPDATE}
        - NGINX_CONFIG=nginx.dev.conf
    ports:
      - 8080:443